version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
      time: "13:30"
      timezone: "Europe/Berlin"
    # Raise pull requests for version updates
    # to cargo against the `feature` branch
    target-branch: "feature/fix-critical-dependency-updates"
    # Labels on pull requests for version updates only
    labels:
      - "cargo dependencies"