on: [push]

name: Tests

jobs:
  test-features-default:
    name: Test build with default features
    runs-on: ubuntu-latest
    steps:
      - name: Checkout vade-evan-bbs
        uses: actions/checkout@v2
      - name: Run cargo test
        run: cargo test --release --no-fail-fast
  test-features-portable:
    name: Test build with --no-default-features --features=portable
    runs-on: ubuntu-latest
    steps:
      - name: Checkout vade-evan-bbs
        uses: actions/checkout@v2
      - name: Run cargo test
        run: cargo test --no-default-features --features=portable --no-fail-fast
  test-features-wasm:
    name: Test build with --no-default-features --features=wasm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout vade-evan-bbs
        uses: actions/checkout@v2
      - name: Run cargo test
        run: cargo test --no-default-features --features=wasm --no-fail-fast
