name: Tests

on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features:
          - name: default
            value: ""
          - name: portable
            value: --no-default-features --features=portable
          - name: wasm
            value: --no-default-features --features=wasm
    name: ${{ matrix.features.name }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --release ${{ matrix.features.value }}
      - name: Run tests
        run: cargo test --no-fail-fast ${{ matrix.features.value }}
      - name: Switch to nightly for udeps
        run: rustup toolchain install nightly
      - name: Update cargo
        run: cargo update
      - name: Install cargo udeps
        run: cargo install cargo-udeps --locked
      - name: Run cargo udeps
        run: cargo +nightly udeps ${{ matrix.features.value }}
