name: Tests

on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features:
          - ""
          - --no-default-features --features=portable
          - --no-default-features --features=wasm
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --release ${{ matrix.features }}
      - name: Run tests
        run: cargo test --no-fail-fast --verbose ${{ matrix.features }}
      - name: Install cargo udeps
        run: cargo install cargo-udeps --locked
      - name: Run cargo udeps
        run: cargo udeps ${{ matrix.features }}
