on: [push]

name: Tests

jobs:
  test:
    runs-on: ubuntu-latest
        defaults:
      run:
        shell: bash
        working-directory: scripts
    steps:
      - name: Checkout vade-evan-bbs
        uses: actions/checkout@v2
        with:
          repository: evannetwork/vade-evan-bbs
          path: 'vade-evan-bbs'
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Checkout vade
        uses: actions/checkout@v2
        with:
          repository: evannetwork/vade
          path: 'vade'
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Checkout vade-evan-substrate
        uses: actions/checkout@v2
        with:
          repository: evannetwork/vade-evan-substrate
          path: 'vade-evan-substrate'
          token: ${{ secrets.ACCESS_TOKEN }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Run cargo test
        run: cd vade-evan-bbs && cargo test --release --all-features --no-fail-fast
        env:
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
          RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'