on: [push]

name: Tests

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout vade-evan-bbs
        uses: actions/checkout@v2
      - name: Run cargo test (default, no-wasm)
        run: cargo test --release --no-fail-fast
      - name: Run cargo test (wasm)
        run: cargo test --no-default-features --features=wasm --no-fail-fast
